name = "raiplayrss"
main = "./worker.ts"
compatibility_date = "2025-06-14"

[env.prod.vars]
RAI_BASE_URL = "https://www.raiplaysound.it/"
FETCH_QUEUE_SIZE = 5
LOG_LEVEL = "info"

[env.staging.vars]
RAI_BASE_URL = "https://www.raiplaysound.it/"
FETCH_QUEUE_SIZE = 5
LOG_LEVEL = "info"
