name = "raiplayrss"
main = "./worker.ts"
compatibility_date = "2024-01-16"

[env.prod.vars]
BASE_URL = "https://raiplayrss.workers.dev/"
RAI_BASE_URL = "https://www.raiplaysound.it/"
FETCH_QUEUE_SIZE = 5
LOG_LEVEL = "info"
