name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    timeout-minutes: 2
    runs-on: ubuntu-22.04
    name: Deploy
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: Install npm dependencies
        run: npm ci
      - name: Deploy
        uses: cloudflare/wrangler-action@7c01cc48d88a1f83b4716e0557c168854a9dcdb8 # v3.4.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: '3.26.0'
          workingDirectory: 'packages/cf'
          command: deploy --env prod
