name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    timeout-minutes: 2
    runs-on: ubuntu-22.04
    name: Deploy
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: Install npm dependencies
        run: npm ci
      - name: Set wrangler version
        id: wrangler
        run: echo "version=$(jq -r .devDependencies.wrangler packages/cf/package.json)" >> "$GITHUB_OUTPUT"
      - name: Deploy
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: ${{ steps.wrangler.outputs.version }}
          workingDirectory: 'packages/cf'
          command: deploy --env ${{ github.ref == 'refs/heads/main' && 'prod' || 'staging' }}
